"""Emit a deterministic docx-js builder script (.mjs) from a typed BuildSpec.

The emitted script reads `spec.json` at runtime and writes the output .docx.
Codegen is straightforward: each spec field maps to a fixed docx-js construct
documented in Anthropic's docx SKILL.md.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

_DIR = Path(__file__).resolve().parent
if str(_DIR) not in sys.path:
    sys.path.insert(0, str(_DIR))

from models import BuildSpec


_PAGE_SIZES = {
    "letter": (12240, 15840),
    "a4":     (11906, 16838),
}


def _find_docx_node_modules() -> Path | None:
    """Return the path to node_modules containing docx, preferring local install."""
    # Check local install in skill directory first
    skill_root = _DIR.parent
    local_nm = skill_root / "node_modules"
    if (local_nm / "docx").exists():
        return local_nm

    # Fall back to global npm root
    try:
        result = subprocess.run(
            ["npm", "root", "-g"],
            capture_output=True,
            text=True,
            check=True,
        )
        global_nm = Path(result.stdout.strip())
        if (global_nm / "docx").exists():
            return global_nm
    except Exception:
        pass

    return None


def emit_builder(spec: BuildSpec, mjs_path: Path, spec_json_path: Path, out_docx: Path) -> None:
    """Write `spec.json` and a `build.mjs` that produces `out_docx` when run by node."""
    spec_json_path.parent.mkdir(parents=True, exist_ok=True)
    spec_json_path.write_text(spec.model_dump_json(indent=2), encoding="utf-8")

    width, height = _PAGE_SIZES.get(spec.page.size.lower(), _PAGE_SIZES["letter"])
    margin_dxa = {
        "top":    int(spec.page.margins.top * 1440),
        "bottom": int(spec.page.margins.bottom * 1440),
        "left":   int(spec.page.margins.left * 1440),
        "right":  int(spec.page.margins.right * 1440),
    }

    # Resolve the node_modules path so the emitted .mjs can import docx
    nm_path = _find_docx_node_modules()
    if nm_path is None:
        raise RuntimeError(
            "Cannot locate docx npm package. Run: npm install docx  (in the skill root)"
        )

    # Emit a file:// URL for the ESM import specifier.
    # The docx package v9+ ships dist/index.mjs as its ESM entry point.
    # On Windows, absolute paths in ESM import() must use the file:// scheme.
    docx_path = nm_path / "docx" / "dist" / "index.mjs"
    docx_import = docx_path.as_uri()  # pathlib.as_uri() produces file:///C:/... on Windows

    template = _BUILDER_TEMPLATE.format(
        spec_json=json.dumps(str(spec_json_path)),
        out_docx=json.dumps(str(out_docx)),
        page_width=width,
        page_height=height,
        margin_top=margin_dxa["top"],
        margin_bottom=margin_dxa["bottom"],
        margin_left=margin_dxa["left"],
        margin_right=margin_dxa["right"],
        landscape="true" if spec.page.orientation.lower() == "landscape" else "false",
        columns=spec.columns if spec.columns > 1 else 1,
        docx_import=json.dumps(docx_import),
    )
    mjs_path.write_text(template, encoding="utf-8")


# The template uses doubled braces {{ }} for JS object literals so that
# Python's str.format() doesn't treat them as placeholders.
_BUILDER_TEMPLATE = r"""// AUTO-GENERATED by word-docx build_js_codegen.py. Do not edit by hand.
import {{ readFileSync, writeFileSync }} from 'node:fs';
import {{
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  PageOrientation, PageNumber, Header, Footer,
  TableOfContents, FootnoteReferenceRun, ExternalHyperlink, InternalHyperlink,
  BookmarkStart, BookmarkEnd,
}} from {docx_import};

// Module-level counter ensures every BookmarkStart/End pair gets a unique w:id.
// docx-js's Bookmark class resets its counter per instance, producing duplicate w:id="1"
// across multiple bookmarks in the same document.  Using BookmarkStart/BookmarkEnd
// directly with an explicit counter avoids that bug.
let _bookmarkCounter = 0;

const spec = JSON.parse(readFileSync({spec_json}, 'utf-8'));

const children = [];

if (spec.title) {{
  children.push(new Paragraph({{ heading: HeadingLevel.TITLE, children: [new TextRun(spec.title)] }}));
}}
if (spec.subtitle) {{
  children.push(new Paragraph({{ children: [new TextRun({{ text: spec.subtitle, italics: true }})] }}));
}}

if (spec.toc) {{
  children.push(new TableOfContents(spec.toc.title || 'Contents', {{
    hyperlink: spec.toc.hyperlinks !== false,
    headingStyleRange: spec.toc.heading_range || '1-3',
  }}));
}}

// Build a map from section heading text -> bookmark anchor, derived from internal_links.
// Heuristic: if a link's label matches a section heading verbatim, that heading is
// wrapped in a Bookmark so InternalHyperlink anchors resolve to an actual target.
const linkLabelToAnchor = new Map();
for (const link of (spec.internal_links || [])) {{
  if (link.label) linkLabelToAnchor.set(link.label, link.anchor);
}}

// Helper: split paragraph text on [^N] markers and return mixed TextRun /
// FootnoteReferenceRun children.  Used only when native_footnotes is non-empty.
function parseParaRuns(text, fnKeys) {{
  if (!fnKeys.size || !/\[\^[0-9]+\]/.test(text)) {{
    return [new TextRun(text)];
  }}
  const runs = [];
  const parts = text.split(/(\[\^[0-9]+\])/);
  for (const part of parts) {{
    const m = part.match(/^\[\^([0-9]+)\]$/);
    if (m && fnKeys.has(m[1])) {{
      runs.push(new FootnoteReferenceRun(Number(m[1])));
    }} else if (part) {{
      runs.push(new TextRun(part));
    }}
  }}
  return runs;
}}

const fnKeys = new Set(Object.keys(spec.native_footnotes || {{}}));

for (const sec of (spec.sections || [])) {{
  const anchor = linkLabelToAnchor.get(sec.heading);
  const headingChildren = anchor
    ? [new BookmarkStart(anchor, ++_bookmarkCounter), new TextRun(sec.heading), new BookmarkEnd(_bookmarkCounter)]
    : [new TextRun(sec.heading)];
  children.push(new Paragraph({{ heading: HeadingLevel.HEADING_1, children: headingChildren }}));
  for (const para of (sec.paragraphs || [])) {{
    children.push(new Paragraph({{ children: parseParaRuns(para, fnKeys) }}));
  }}
}}

for (const item of (spec.items || [])) {{
  children.push(new Paragraph({{ heading: HeadingLevel.HEADING_2, children: [new TextRun(item.comment_id + ': ' + (item.comment || ''))] }}));
  if (item.response) children.push(new Paragraph({{ children: [new TextRun(item.response)] }}));
  if (item.revision_made) children.push(new Paragraph({{ children: [new TextRun({{ text: 'Revision: ' + item.revision_made, italics: true }})] }}));
}}

for (const link of (spec.internal_links || [])) {{
  children.push(new Paragraph({{
    children: [new InternalHyperlink({{
      children: [new TextRun({{ text: link.text || link.label, style: 'Hyperlink' }})],
      anchor: link.anchor,
    }})],
  }}));
}}

const headers = {{}};
const footers = {{}};
for (const ps of (spec.page_sections || [])) {{
  if (ps.header && ps.header.length) {{
    const runs = ps.header.map(el => el.type === 'page_number'
      ? new TextRun({{ children: [PageNumber.CURRENT] }})
      : new TextRun(el.value || ''));
    headers.default = new Header({{ children: [new Paragraph({{ children: runs }})] }});
  }}
  if (ps.footer && ps.footer.length) {{
    const runs = ps.footer.map(el => el.type === 'page_number'
      ? new TextRun({{ children: [PageNumber.CURRENT] }})
      : new TextRun(el.value || ''));
    footers.default = new Footer({{ children: [new Paragraph({{ children: runs }})] }});
  }}
}}

const footnotes = {{}};
for (const [k, v] of Object.entries(spec.native_footnotes || {{}})) {{
  footnotes[Number(k)] = {{ children: [new Paragraph({{ children: [new TextRun(v)] }})] }};
}}

const sectionProps = {{
  page: {{
    size: {{
      width: {page_width}, height: {page_height},
      orientation: {landscape} ? PageOrientation.LANDSCAPE : PageOrientation.PORTRAIT,
    }},
    margin: {{ top: {margin_top}, bottom: {margin_bottom}, left: {margin_left}, right: {margin_right} }},
  }},
}};
if ({columns} > 1) {{
  sectionProps.column = {{ count: {columns}, space: 720, equalWidth: true, separate: false }};
}}

const doc = new Document({{
  footnotes,
  sections: [{{
    properties: sectionProps,
    headers,
    footers,
    children,
  }}],
}});

Packer.toBuffer(doc).then(buf => writeFileSync({out_docx}, buf));
"""
